services:
  api:
    build:
      context: ../..
      dockerfile: deploy/docker/api.Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      MONGODB_URI: "mongodb://mongodb:27017"
      MONGODB_DB: "taskdb"
      MONGODB_COLLECTION: "tasks"
      CORS_ALLOW_ORIGINS: "http://localhost:8081,http://127.0.0.1:8081"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ../..
      dockerfile: deploy/docker/frontend.Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - api

  mongodb:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_ALLOW_EMPTY_PASSWORD: "yes"
      MONGODB_DATABASE: "taskdb"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/bitnami/mongodb

volumes:
  mongodb_data:
