apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-api-huma-mongo.frontendName" . }}
  labels:
    {{- include "task-api-huma-mongo.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
  selector:
    {{- include "task-api-huma-mongo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
