apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-api-huma-mongo.apiName" . }}
  labels:
    {{- include "task-api-huma-mongo.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
  selector:
    {{- include "task-api-huma-mongo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
