{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "task-api-huma-mongo.serviceAccountName" . }}
  labels:
    {{- include "task-api-huma-mongo.labels" . | nindent 4 }}
{{- end }}
